# Generated by Django 5.2.7 on 2025-11-02 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id_cliente", models.AutoField(primary_key=True, serialize=False)),
                ("rut", models.CharField(max_length=12, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("direccion", models.CharField(blank=True, max_length=200, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("comuna", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("fecha_registro", models.DateTimeField(blank=True, null=True)),
                ("estado", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "cliente",
            },
        ),
        migrations.CreateModel(
            name="Constructora",
            fields=[
                (
                    "id_constructora",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("rut", models.CharField(max_length=15, unique=True)),
                ("razon_social", models.CharField(max_length=150)),
                (
                    "nombre_fantasia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "email_contacto",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("direccion", models.CharField(blank=True, max_length=200, null=True)),
                ("sitio_web", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "representante_legal",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("estado", models.CharField(blank=True, max_length=20, null=True)),
                ("fecha_registro", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "constructora",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id_material", models.AutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        blank=True, db_column="categoria", max_length=50, null=True
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("proveedor", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "costo_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("stock_actual", models.IntegerField(blank=True, null=True)),
                ("stock_minimo", models.IntegerField(blank=True, null=True)),
                (
                    "ubicacion_bodega",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "material",
            },
        ),
        migrations.CreateModel(
            name="Tecnico",
            fields=[
                ("id_tecnico", models.AutoField(primary_key=True, serialize=False)),
                ("rut", models.CharField(max_length=12, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "especialidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "zona_cobertura",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("disponibilidad_horaria", models.JSONField(blank=True, null=True)),
                ("casos_activos", models.IntegerField(blank=True, null=True)),
                (
                    "calificacion_promedio",
                    models.DecimalField(
                        db_column="calificacion_promedio",
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                    ),
                ),
                ("estado", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "tecnico",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("rut", models.CharField(max_length=12, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("password_hash", models.CharField(max_length=200)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("propietario", "Propietario"),
                            ("tecnico", "Técnico"),
                            ("supervisor", "Supervisor"),
                            ("administrador", "Administrador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(blank=True, null=True)),
                ("ultimo_acceso", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "usuario",
            },
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                ("id_proyecto", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.TextField(blank=True, null=True)),
                (
                    "tipo_proyecto",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("fecha_entrega", models.DateField(blank=True, null=True)),
                (
                    "constructora_responsable",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cantidad_unidades", models.IntegerField(blank=True, null=True)),
                ("estado", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "id_cliente",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cliente",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proyectos_cliente",
                        to="postventa_app.cliente",
                    ),
                ),
                (
                    "id_constructora",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_constructora",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proyectos_constructora",
                        to="postventa_app.constructora",
                    ),
                ),
            ],
            options={
                "db_table": "proyecto",
            },
        ),
        migrations.CreateModel(
            name="Reclamo",
            fields=[
                ("id_reclamo", models.AutoField(primary_key=True, serialize=False)),
                ("numero_folio", models.CharField(max_length=20, unique=True)),
                ("titulo", models.CharField(blank=True, max_length=200, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("categoria", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "ubicacion_especifica",
                    models.CharField(
                        blank=True,
                        db_column="ubicacion_especifica",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("fecha_ingreso", models.DateTimeField(blank=True, null=True)),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                (
                    "tiempo_estimado_horas",
                    models.IntegerField(
                        blank=True, db_column="tiempo_estimado_horas", null=True
                    ),
                ),
                ("estado", models.CharField(blank=True, max_length=50, null=True)),
                ("prioridad", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "requiere_aprobacion",
                    models.BooleanField(db_column="requiere_aprobacion", default=False),
                ),
                (
                    "id_cliente",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cliente",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reclamos_cliente",
                        to="postventa_app.cliente",
                    ),
                ),
                (
                    "id_proyecto",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_proyecto",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reclamos_proyecto",
                        to="postventa_app.proyecto",
                    ),
                ),
            ],
            options={
                "db_table": "reclamo",
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id_notificacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("tipo", models.CharField(blank=True, max_length=50, null=True)),
                ("mensaje", models.CharField(blank=True, max_length=200, null=True)),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("leido", models.BooleanField(default=False)),
                (
                    "id_reclamo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_reclamo",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="postventa_app.reclamo",
                    ),
                ),
            ],
            options={
                "db_table": "notificacion",
            },
        ),
        migrations.CreateModel(
            name="ArchivoEvidencia",
            fields=[
                ("id_archivo", models.AutoField(primary_key=True, serialize=False)),
                ("url_s3", models.TextField(blank=True, null=True)),
                ("tipo", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "nombre_original",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "tamano_kb",
                    models.IntegerField(blank=True, db_column="tamano_kb", null=True),
                ),
                ("fecha_subida", models.DateTimeField(blank=True, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "id_reclamo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_reclamo",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos_evidencia",
                        to="postventa_app.reclamo",
                    ),
                ),
            ],
            options={
                "db_table": "archivoEvidencia",
            },
        ),
        migrations.CreateModel(
            name="Cita",
            fields=[
                ("id_cita", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_programada", models.DateTimeField(blank=True, null=True)),
                ("fecha_confirmacion", models.DateTimeField(blank=True, null=True)),
                ("estado", models.CharField(blank=True, max_length=20, null=True)),
                ("tipo_cita", models.CharField(blank=True, max_length=50, null=True)),
                ("motivo_reprogramacion", models.TextField(blank=True, null=True)),
                ("recordatorio_enviado", models.BooleanField(default=False)),
                (
                    "duracion_estimada_minutos",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "id_cliente",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cliente",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citas",
                        to="postventa_app.cliente",
                    ),
                ),
                (
                    "id_reclamo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_reclamo",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citas",
                        to="postventa_app.reclamo",
                    ),
                ),
                (
                    "id_tecnico",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_tecnico",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citas",
                        to="postventa_app.tecnico",
                    ),
                ),
            ],
            options={
                "db_table": "cita",
            },
        ),
        migrations.CreateModel(
            name="AsignacionTecnico",
            fields=[
                ("id_asignacion", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_asignacion", models.DateTimeField(blank=True, null=True)),
                (
                    "metodo_asignacion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("puntuacion_match", models.IntegerField(blank=True, null=True)),
                ("estado", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "id_reclamo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_reclamo",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="postventa_app.reclamo",
                    ),
                ),
                (
                    "id_tecnico",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_tecnico",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="postventa_app.tecnico",
                    ),
                ),
            ],
            options={
                "db_table": "asignacionTecnico",
            },
        ),
        migrations.CreateModel(
            name="Historial",
            fields=[
                ("id_historial", models.AutoField(primary_key=True, serialize=False)),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True,
                        db_column="estado_anterior",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("fecha_cambio", models.DateTimeField(blank=True, null=True)),
                ("motivo", models.TextField(blank=True, null=True)),
                (
                    "id_reclamo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_reclamo",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="postventa_app.reclamo",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_usuario",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="postventa_app.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "historial",
            },
        ),
        migrations.CreateModel(
            name="VisitaTecnica",
            fields=[
                ("id_visita", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_visita", models.DateTimeField(blank=True, null=True)),
                ("estado", models.CharField(blank=True, max_length=20, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "duracion_real_minutos",
                    models.IntegerField(
                        blank=True, db_column="duracion_real_minutos", null=True
                    ),
                ),
                (
                    "tipo_trabajo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("requiere_seguimiento", models.BooleanField(default=False)),
                ("fecha_proxima_visita", models.DateField(blank=True, null=True)),
                (
                    "id_cita",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cita",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitas_tecnicas",
                        to="postventa_app.cita",
                    ),
                ),
                (
                    "id_reclamo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_reclamo",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitas_tecnicas",
                        to="postventa_app.reclamo",
                    ),
                ),
                (
                    "id_tecnico",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_tecnico",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitas_tecnicas",
                        to="postventa_app.tecnico",
                    ),
                ),
            ],
            options={
                "db_table": "visitaTecnica",
            },
        ),
        migrations.CreateModel(
            name="UsoMaterial",
            fields=[
                ("id_uso", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad_usada", models.IntegerField(blank=True, null=True)),
                ("fecha_uso", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "id_material",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_material",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usos",
                        to="postventa_app.material",
                    ),
                ),
                (
                    "id_visita",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_visita",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usos_materiales",
                        to="postventa_app.visitatecnica",
                    ),
                ),
            ],
            options={
                "db_table": "usoMaterial",
            },
        ),
        migrations.CreateModel(
            name="GestionEscombros",
            fields=[
                ("id_escombro", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_escombro",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "volumen_m3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("fecha_programada_retiro", models.DateField(blank=True, null=True)),
                ("fecha_real_retiro", models.DateField(blank=True, null=True)),
                ("estado", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "empresa_retiro",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "costo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "id_reclamo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_reclamo",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gestion_escombros",
                        to="postventa_app.reclamo",
                    ),
                ),
                (
                    "id_visita",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_visita",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gestion_escombros",
                        to="postventa_app.visitatecnica",
                    ),
                ),
            ],
            options={
                "db_table": "gestionEscombros",
            },
        ),
        migrations.CreateModel(
            name="EncuestaSatisfaccion",
            fields=[
                ("id_encuesta", models.AutoField(primary_key=True, serialize=False)),
                (
                    "puntuacion",
                    models.IntegerField(blank=True, db_column="puntuacion", null=True),
                ),
                ("comentarios", models.TextField(blank=True, null=True)),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                ("calificacion_tecnico", models.IntegerField(blank=True, null=True)),
                (
                    "calificacion_tiempo",
                    models.IntegerField(
                        blank=True, db_column="calificacion_tiempo", null=True
                    ),
                ),
                ("calificacion_solucion", models.IntegerField(blank=True, null=True)),
                (
                    "id_reclamo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_reclamo",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encuestas",
                        to="postventa_app.reclamo",
                    ),
                ),
                (
                    "id_visita",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_visita",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encuestas",
                        to="postventa_app.visitatecnica",
                    ),
                ),
            ],
            options={
                "db_table": "encuestaSatisfaccion",
            },
        ),
    ]
