# Generated by Django 5.2.7 on 2025-11-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reclamo",
            name="unidad",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
