# Generated by Django 5.2.7 on 2025-11-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0002_reclamo_unidad"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archivoevidencia",
            options={
                "verbose_name": "Archivo Evidencia",
                "verbose_name_plural": "Archivos Evidencias",
            },
        ),
        migrations.AlterModelOptions(
            name="asignaciontecnico",
            options={
                "verbose_name": "Asignación Técnico",
                "verbose_name_plural": "Asignaciones Técnicos",
            },
        ),
        migrations.AlterModelOptions(
            name="cita",
            options={"verbose_name": "Cita", "verbose_name_plural": "Citas"},
        ),
        migrations.AlterModelOptions(
            name="cliente",
            options={"verbose_name": "Cliente", "verbose_name_plural": "Clientes"},
        ),
        migrations.AlterModelOptions(
            name="constructora",
            options={
                "verbose_name": "Constructora",
                "verbose_name_plural": "Constructoras",
            },
        ),
        migrations.AlterModelOptions(
            name="encuestasatisfaccion",
            options={
                "verbose_name": "Encuesta Satisfacción",
                "verbose_name_plural": "Encuestas Satisfacción",
            },
        ),
        migrations.AlterModelOptions(
            name="gestionescombros",
            options={
                "verbose_name": "Gestión Escombros",
                "verbose_name_plural": "Gestiones Escombros",
            },
        ),
        migrations.AlterModelOptions(
            name="historial",
            options={"verbose_name": "Historial", "verbose_name_plural": "Historiales"},
        ),
        migrations.AlterModelOptions(
            name="material",
            options={"verbose_name": "Material", "verbose_name_plural": "Materiales"},
        ),
        migrations.AlterModelOptions(
            name="notificacion",
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="proyecto",
            options={"verbose_name": "Proyecto", "verbose_name_plural": "Proyectos"},
        ),
        migrations.AlterModelOptions(
            name="reclamo",
            options={"verbose_name": "Reclamo", "verbose_name_plural": "Reclamos"},
        ),
        migrations.AlterModelOptions(
            name="tecnico",
            options={"verbose_name": "Técnico", "verbose_name_plural": "Técnicos"},
        ),
        migrations.AlterModelOptions(
            name="usomaterial",
            options={
                "verbose_name": "Uso Material",
                "verbose_name_plural": "Usos Materiales",
            },
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={"verbose_name": "Usuario", "verbose_name_plural": "Usuarios"},
        ),
        migrations.AlterModelOptions(
            name="visitatecnica",
            options={
                "verbose_name": "Visita Técnica",
                "verbose_name_plural": "Visitas Técnicas",
            },
        ),
    ]
