# Generated by Django 5.2.7 on 2025-11-02 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0003_alter_archivoevidencia_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tecnico",
            name="constructora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tecnicos",
                to="postventa_app.constructora",
            ),
        ),
    ]
