# Generated by Django 5.2.7 on 2025-11-02 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0005_especialidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tecnico",
            name="especialidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tecnicos",
                to="postventa_app.especialidad",
            ),
        ),
    ]
