# Generated by Django 5.2.7 on 2025-11-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0006_alter_tecnico_especialidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("entregado", "Entregado"),
                    ("en garantia", "En garantía"),
                    ("finalizado", "Finalizado"),
                ],
                default="entregado",
                max_length=20,
            ),
        ),
    ]
