# Generated by Django 5.2.7 on 2025-11-03 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0008_cliente_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="unidad",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="Unidad",
            fields=[
                ("id_unidad", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unidades",
                        to="postventa_app.cliente",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades",
                        to="postventa_app.proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad",
                "verbose_name_plural": "Unidades",
                "db_table": "unidad",
            },
        ),
    ]
