# Generated by Django 5.2.7 on 2025-11-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0009_cliente_unidad_unidad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archivoevidencia",
            name="url_s3",
        ),
        migrations.AddField(
            model_name="archivoevidencia",
            name="archivo",
            field=models.FileField(blank=True, null=True, upload_to="evidencias/"),
        ),
    ]
