# Generated by Django 5.2.7 on 2025-11-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0010_remove_archivoevidencia_url_s3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reclamo",
            name="descripcion",
            field=models.TextField(null=True),
        ),
    ]
