# Generated by Django 5.2.7 on 2025-11-05 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0011_alter_reclamo_descripcion"),
    ]

    operations = []
