# Generated by Django 5.2.7 on 2025-11-05 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0012_add_missing_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Nombre de categoría"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="proyecto",
            name="codigo",
            field=models.CharField(
                default="",
                max_length=50,
                unique=True,
                verbose_name="Código del proyecto",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="constructora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proyectos",
                to="postventa_app.constructora",
                verbose_name="Constructora",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="encargado",
            field=models.CharField(
                blank=True,
                max_length=120,
                null=True,
                verbose_name="Encargado del proyecto",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="fecha_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de inicio"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="observaciones",
            field=models.TextField(blank=True, null=True, verbose_name="Observaciones"),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="telefono_encargado",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Teléfono encargado"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="ubicacion",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Ubicación"
            ),
        ),
        migrations.AddField(
            model_name="reclamo",
            name="fecha_asignacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reclamo",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reclamos",
                to="postventa_app.proyecto",
            ),
        ),
        migrations.AddField(
            model_name="reclamo",
            name="tecnico_asignado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reclamos_asignados",
                to="postventa_app.tecnico",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="codigo",
            field=models.CharField(default="", max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("entregado", "Entregado"),
                    ("garantia", "En Garantía"),
                    ("finalizado", "Finalizado"),
                ],
                default="entregado",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reclamo",
            name="estado",
            field=models.CharField(
                choices=[
                    ("ingresado", "Ingresado"),
                    ("asignado", "Asignado"),
                    ("en_ejecucion", "En Ejecución"),
                    ("completado", "Completado"),
                    ("cancelado", "Cancelado"),
                ],
                default="ingresado",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="reclamo",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reclamos",
                to="postventa_app.categoria",
            ),
        ),
        migrations.CreateModel(
            name="Propietario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=120, verbose_name="Nombre completo"),
                ),
                ("rut", models.CharField(max_length=12, verbose_name="RUT/DNI")),
                (
                    "tipo_propietario",
                    models.CharField(
                        choices=[
                            ("natural", "Persona Natural"),
                            ("juridica", "Persona Jurídica"),
                        ],
                        default="natural",
                        max_length=10,
                        verbose_name="Tipo de propietario",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                ("telefono", models.CharField(max_length=30, verbose_name="Teléfono")),
                (
                    "telefono_alternativo",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Teléfono alternativo",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=200, verbose_name="Dirección"),
                ),
                (
                    "unidad",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Unidad/Departamento",
                    ),
                ),
                (
                    "fecha_compra",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de compra"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        default="activo",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "notas_internas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas internas"
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="propietarios",
                        to="postventa_app.proyecto",
                        verbose_name="Proyecto de vivienda",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propietarios",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario del sistema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Propietario",
                "verbose_name_plural": "Propietarios",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="reclamo",
            name="propietario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reclamos",
                to="postventa_app.propietario",
            ),
        ),
    ]
