# Generated by Django 5.2.7 on 2025-11-05 21:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "postventa_app",
            "0013_categoria_proyecto_codigo_proyecto_constructora_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="fecha_registro",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha de registro",
            ),
            preserve_default=False,
        ),
    ]
