# Generated by Django 5.2.7 on 2025-11-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0014_proyecto_fecha_registro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proyecto",
            name="constructora_responsable",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="id_cliente",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="id_constructora",
        ),
    ]
