# Generated by Django 5.2.7 on 2025-11-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0015_remove_proyecto_constructora_responsable_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proyecto",
            name="ubicacion",
        ),
    ]
