# Generated by Django 5.2.7 on 2025-11-05 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0016_remove_proyecto_ubicacion"),
    ]

    operations = [
        # First, clear all foreign keys that reference Cliente to avoid constraint violations
        migrations.RunSQL(
            "UPDATE unidad SET cliente_id = NULL WHERE cliente_id IS NOT NULL",
            "-- no-op reverse",
        ),
        migrations.RunSQL(
            "UPDATE reclamo SET id_cliente = NULL WHERE id_cliente IS NOT NULL",
            "-- no-op reverse",
        ),
        migrations.RunSQL(
            "UPDATE cita SET id_cliente = NULL WHERE id_cliente IS NOT NULL",
            "-- no-op reverse",
        ),
        # Now alter the fields to point to Propietario instead of Cliente
        migrations.AlterField(
            model_name="reclamo",
            name="id_cliente",
            field=models.ForeignKey(
                blank=True,
                db_column="id_cliente",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reclamos_cliente",
                to="postventa_app.propietario",
            ),
        ),
        migrations.AlterField(
            model_name="cita",
            name="id_cliente",
            field=models.ForeignKey(
                blank=True,
                db_column="id_cliente",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citas",
                to="postventa_app.propietario",
            ),
        ),
        migrations.AlterField(
            model_name="unidad",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unidades",
                to="postventa_app.propietario",
            ),
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
    ]
