# Generated by Django 5.2.7 on 2025-11-05 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "postventa_app",
            "0017_alter_reclamo_id_cliente_alter_cita_id_cliente_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reclamo",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reclamos",
                to="postventa_app.especialidad",
            ),
        ),
    ]
