# Generated by Django 5.2.7 on 2025-11-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0018_alter_reclamo_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cita",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pendiente", "Pendiente"),
                    ("confirmada", "Confirmada"),
                    ("en_curso", "En Curso"),
                    ("completada", "Completada"),
                    ("cancelada", "Cancelada"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
