# Generated by Django 5.2.7 on 2025-11-06 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0019_alter_cita_estado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propietario",
            options={},
        ),
        migrations.RemoveField(
            model_name="propietario",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="propietario",
            name="fecha_compra",
        ),
        migrations.RemoveField(
            model_name="propietario",
            name="fecha_registro",
        ),
        migrations.RemoveField(
            model_name="propietario",
            name="notas_internas",
        ),
        migrations.RemoveField(
            model_name="propietario",
            name="unidad",
        ),
        migrations.RemoveField(
            model_name="reclamo",
            name="id_cliente",
        ),
        migrations.RemoveField(
            model_name="reclamo",
            name="id_proyecto",
        ),
        migrations.AlterField(
            model_name="propietario",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="propietario",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario del sistema",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reclamo",
            name="propietario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reclamos",
                to="postventa_app.propietario",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reclamo",
            name="proyecto",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reclamos",
                to="postventa_app.proyecto",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("administrador", "Administrador"),
                            ("supervisor", "Supervisor"),
                            ("tecnico", "Técnico"),
                            ("propietario", "Propietario"),
                        ],
                        max_length=20,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
                ("direccion", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
