# Generated by Django 5.2.7 on 2025-11-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "postventa_app",
            "0020_alter_propietario_options_remove_propietario_estado_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="extra",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
