# Generated by Django 5.2.7 on 2025-11-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0021_perfil_extra"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perfil",
            options={"verbose_name": "Perfil", "verbose_name_plural": "Perfiles"},
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="extra",
        ),
    ]
