# Generated by Django 5.2.7 on 2025-11-06 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0022_alter_perfil_options_remove_perfil_extra"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tecnico",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tecnico",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario del sistema",
            ),
        ),
    ]
