# Generated by Django 5.2.7 on 2025-11-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0023_tecnico_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="reclamo",
            name="resolucion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
