# Generated by Django 5.2.7 on 2025-11-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0024_reclamo_resolucion"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitatecnica",
            name="fecha_cierre",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
