# Generated by Django 5.2.7 on 2025-11-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0025_visitatecnica_fecha_cierre"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivoevidencia",
            name="subido_por",
            field=models.CharField(
                choices=[
                    ("cliente", "Cliente"),
                    ("tecnico", "Técnico"),
                    ("sistema", "Sistema"),
                ],
                default="cliente",
                help_text="Quién subió este archivo",
                max_length=20,
            ),
        ),
    ]
