# Generated by Django 5.2.7 on 2025-11-16 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0026_add_subido_por_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reclamo",
            name="titulo",
        ),
        migrations.CreateModel(
            name="Disponibilidad",
            fields=[
                (
                    "id_disponibilidad",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "fecha",
                    models.DateField(
                        db_column="fecha",
                        help_text="Fecha del día para el cual se especifica disponibilidad",
                    ),
                ),
                (
                    "hora_inicio",
                    models.TimeField(
                        db_column="hora_inicio",
                        help_text="Hora de inicio de disponibilidad (HH:MM)",
                    ),
                ),
                (
                    "hora_fin",
                    models.TimeField(
                        db_column="hora_fin",
                        help_text="Hora de fin de disponibilidad (HH:MM)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "id_tecnico",
                    models.ForeignKey(
                        db_column="id_tecnico",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disponibilidades",
                        to="postventa_app.tecnico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disponibilidad",
                "verbose_name_plural": "Disponibilidades",
                "db_table": "disponibilidad",
                "ordering": ["fecha", "hora_inicio"],
                "unique_together": {("id_tecnico", "fecha", "hora_inicio", "hora_fin")},
            },
        ),
    ]
