# Generated by Django 5.2.7 on 2025-11-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0027_remove_reclamo_titulo_disponibilidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivoevidencia",
            name="archivo",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="evidencias/"
            ),
        ),
    ]
