# Generated by Django 5.2.7 on 2025-11-16 02:04

import postventa_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0028_alter_archivoevidencia_archivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivoevidencia",
            name="archivo",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                storage=postventa_app.models.NombreOriginalStorage(),
                upload_to=postventa_app.models.archivo_path,
            ),
        ),
    ]
