# Generated by Django 5.2.7 on 2025-11-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0029_alter_archivoevidencia_archivo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tecnico",
            name="disponibilidad_horaria",
        ),
    ]
