# Generated by Django 5.2.7 on 2025-11-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0030_remove_disponibilidad_horaria_from_tecnico"),
    ]

    operations = [
        migrations.AddField(
            model_name="disponibilidad",
            name="dia_semana",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Lunes"),
                    (1, "Martes"),
                    (2, "Miércoles"),
                    (3, "Jueves"),
                    (4, "Viernes"),
                    (5, "Sábado"),
                    (6, "Domingo"),
                ],
                db_column="dia_semana",
                help_text="Día de la semana para horarios recurrentes (0=Lunes, 6=Domingo)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="disponibilidad",
            name="es_recurrente",
            field=models.BooleanField(
                db_column="es_recurrente",
                default=False,
                help_text="Si es True, este horario se repite cada semana en el mismo día",
            ),
        ),
    ]
