# Generated by Django 5.2.7 on 2025-11-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0031_add_recurrencia_disponibilidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reclamo",
            name="estado",
            field=models.CharField(
                choices=[
                    ("ingresado", "Ingresado"),
                    ("asignado", "Asignado"),
                    ("en_ejecucion", "En Ejecución"),
                    ("en_proceso", "En Proceso"),
                    ("completado", "Completado"),
                    ("resuelto", "Resuelto"),
                    ("cancelado", "Cancelado"),
                ],
                default="ingresado",
                max_length=50,
            ),
        ),
    ]
