# Generated by Django 5.2.7 on 2025-11-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0037_tipos_escombro_actualizado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gestionescombros",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pendiente", "Pendiente"),
                    ("programado", "Programado"),
                    ("completado", "Completado"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendiente",
                max_length=20,
                null=True,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="gestionescombros",
            name="tipo_escombro",
            field=models.CharField(
                blank=True,
                choices=[
                    ("construccion", "Construcción"),
                    ("muebles_madera", "Muebles o madera"),
                    ("metales", "Metales"),
                    ("plasticos_carton", "Plásticos / cartón"),
                    ("vidrio", "Vidrio"),
                    ("mixto", "Mixto"),
                    ("otro", "Otro"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de escombro",
            ),
        ),
        migrations.AlterField(
            model_name="reclamo",
            name="estado",
            field=models.CharField(
                choices=[
                    ("ingresado", "Ingresado"),
                    ("asignado", "Asignado"),
                    ("en_ejecucion", "En Ejecución"),
                    ("en_proceso", "En Proceso"),
                    ("completado", "Completado"),
                    ("resuelto", "Reclamo Resuelto"),
                    ("cancelado", "Cancelado"),
                ],
                default="ingresado",
                max_length=50,
            ),
        ),
    ]
