# Generated by Django 5.2.7 on 2025-11-18 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0038_alter_gestionescombros_estado_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="encuestasatisfaccion",
            options={
                "ordering": ["-fecha_envio"],
                "verbose_name": "Encuesta de Satisfacción",
                "verbose_name_plural": "Encuestas de Satisfacción",
            },
        ),
        migrations.RemoveField(
            model_name="encuestasatisfaccion",
            name="calificacion_solucion",
        ),
        migrations.RemoveField(
            model_name="encuestasatisfaccion",
            name="calificacion_tecnico",
        ),
        migrations.RemoveField(
            model_name="encuestasatisfaccion",
            name="calificacion_tiempo",
        ),
        migrations.RemoveField(
            model_name="encuestasatisfaccion",
            name="comentarios",
        ),
        migrations.RemoveField(
            model_name="encuestasatisfaccion",
            name="fecha_respuesta",
        ),
        migrations.RemoveField(
            model_name="encuestasatisfaccion",
            name="id_visita",
        ),
        migrations.RemoveField(
            model_name="encuestasatisfaccion",
            name="puntuacion",
        ),
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="created_at",
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="email_propietario",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Email del Propietario",
            ),
        ),
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente de envío"),
                    ("enviada", "Enviada"),
                    ("completada", "Completada"),
                    ("cancelada", "Cancelada"),
                ],
                default="pendiente",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="fecha_completada",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Completación"
            ),
        ),
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="fecha_envio",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Envío"
            ),
        ),
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="link_encuesta",
            field=models.URLField(
                blank=True,
                help_text="URL de Google Forms u otra encuesta externa",
                null=True,
                verbose_name="Link de la Encuesta",
            ),
        ),
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="nombre_propietario",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Nombre del Propietario",
            ),
        ),
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="nota",
            field=models.TextField(
                blank=True,
                help_text="Notas internas sobre esta encuesta",
                null=True,
                verbose_name="Notas",
            ),
        ),
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_column="updated_at"),
        ),
        migrations.AlterField(
            model_name="encuestasatisfaccion",
            name="id_encuesta",
            field=models.AutoField(
                db_column="id_encuesta", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterModelTable(
            name="encuestasatisfaccion",
            table="encuesta_satisfaccion",
        ),
    ]
