# Generated by Django 5.2.7 on 2025-11-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0039_alter_encuestasatisfaccion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="calificacion_solucion",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 - Muy insatisfecho"),
                    (2, "2 - Insatisfecho"),
                    (3, "3 - Neutral"),
                    (4, "4 - Satisfecho"),
                    (5, "5 - Muy satisfecho"),
                ],
                null=True,
                verbose_name="Calificación de la Solución",
            ),
        ),
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="calificacion_tecnico",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 - Muy insatisfecho"),
                    (2, "2 - Insatisfecho"),
                    (3, "3 - Neutral"),
                    (4, "4 - Satisfecho"),
                    (5, "5 - Muy satisfecho"),
                ],
                null=True,
                verbose_name="Calificación del Técnico",
            ),
        ),
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="calificacion_tiempo",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 - Muy insatisfecho"),
                    (2, "2 - Insatisfecho"),
                    (3, "3 - Neutral"),
                    (4, "4 - Satisfecho"),
                    (5, "5 - Muy satisfecho"),
                ],
                null=True,
                verbose_name="Calificación del Tiempo de Respuesta",
            ),
        ),
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="comentarios",
            field=models.TextField(
                blank=True, null=True, verbose_name="Comentarios del Propietario"
            ),
        ),
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="puntuacion",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 - Muy insatisfecho"),
                    (2, "2 - Insatisfecho"),
                    (3, "3 - Neutral"),
                    (4, "4 - Satisfecho"),
                    (5, "5 - Muy satisfecho"),
                ],
                null=True,
                verbose_name="Puntuación General",
            ),
        ),
    ]
