# Generated by Django 5.2.7 on 2025-11-18 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0041_usuario_proyecto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historial",
            name="id_usuario",
            field=models.ForeignKey(
                blank=True,
                db_column="id_usuario",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="perfil",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervisores",
                to="postventa_app.proyecto",
                verbose_name="Proyecto asignado",
            ),
        ),
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
