# Generated by Django 5.2.7 on 2025-11-20 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0042_alter_historial_id_usuario_perfil_proyecto_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="encuestasatisfaccion",
            options={
                "verbose_name": "Encuesta Satisfacción",
                "verbose_name_plural": "Encuestas Satisfacción",
            },
        ),
        migrations.RemoveField(
            model_name="encuestasatisfaccion",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="encuestasatisfaccion",
            name="email_propietario",
        ),
        migrations.RemoveField(
            model_name="encuestasatisfaccion",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="encuestasatisfaccion",
            name="fecha_completada",
        ),
        migrations.RemoveField(
            model_name="encuestasatisfaccion",
            name="fecha_envio",
        ),
        migrations.RemoveField(
            model_name="encuestasatisfaccion",
            name="link_encuesta",
        ),
        migrations.RemoveField(
            model_name="encuestasatisfaccion",
            name="nombre_propietario",
        ),
        migrations.RemoveField(
            model_name="encuestasatisfaccion",
            name="nota",
        ),
        migrations.RemoveField(
            model_name="encuestasatisfaccion",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="fecha_respuesta",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="encuestasatisfaccion",
            name="id_visita",
            field=models.ForeignKey(
                blank=True,
                db_column="id_visita",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encuestas",
                to="postventa_app.visitatecnica",
            ),
        ),
        migrations.AlterField(
            model_name="encuestasatisfaccion",
            name="calificacion_solucion",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="encuestasatisfaccion",
            name="calificacion_tecnico",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="encuestasatisfaccion",
            name="calificacion_tiempo",
            field=models.IntegerField(
                blank=True, db_column="calificacion_tiempo", null=True
            ),
        ),
        migrations.AlterField(
            model_name="encuestasatisfaccion",
            name="comentarios",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="encuestasatisfaccion",
            name="id_encuesta",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="encuestasatisfaccion",
            name="puntuacion",
            field=models.IntegerField(blank=True, db_column="puntuacion", null=True),
        ),
        migrations.AlterModelTable(
            name="encuestasatisfaccion",
            table="encuestaSatisfaccion",
        ),
        migrations.CreateModel(
            name="AsignacionEscombros",
            fields=[
                ("id_asignacion", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("asignado", "Asignado"),
                            ("aceptado", "Aceptado"),
                            ("rechazado", "Rechazado"),
                            ("completado", "Completado"),
                        ],
                        default="asignado",
                        max_length=20,
                        verbose_name="Estado de Asignación",
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "id_escombro",
                    models.ForeignKey(
                        db_column="id_escombro",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="postventa_app.gestionescombros",
                        verbose_name="Escombro",
                    ),
                ),
                (
                    "id_tecnico",
                    models.ForeignKey(
                        db_column="id_tecnico",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_escombros",
                        to="postventa_app.tecnico",
                        verbose_name="Técnico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación Escombros",
                "verbose_name_plural": "Asignaciones Escombros",
                "db_table": "asignacionEscombros",
                "unique_together": {("id_escombro", "id_tecnico")},
            },
        ),
    ]
