# Generated by Django 5.2.7 on 2025-11-20 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0043_alter_encuestasatisfaccion_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmpresaRetiro",
            fields=[
                ("id_empresa", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nombre de Empresa"
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("activa", models.BooleanField(default=True, verbose_name="¿Activa?")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Empresa de Retiro",
                "verbose_name_plural": "Empresas de Retiro",
                "db_table": "empresaRetiro",
            },
        ),
        migrations.RemoveField(
            model_name="gestionescombros",
            name="empresa_retiro",
        ),
        migrations.AddField(
            model_name="gestionescombros",
            name="id_empresa_retiro",
            field=models.ForeignKey(
                blank=True,
                db_column="id_empresa_retiro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gestiones_escombros",
                to="postventa_app.empresaretiro",
                verbose_name="Empresa de Retiro",
            ),
        ),
    ]
