# Generated by Django 5.2.7 on 2025-11-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "postventa_app",
            "0044_empresaretiro_remove_gestionescombros_empresa_retiro_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="rut",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="RUT/DNI"
            ),
        ),
    ]
