# Generated by Django 5.2.7 on 2025-10-23 22:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Nombre de categoría"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=120, verbose_name="Nombre completo"),
                ),
                (
                    "rut",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="RUT/DNI"
                    ),
                ),
                (
                    "tipo_cliente",
                    models.CharField(
                        choices=[
                            ("natural", "Persona Natural"),
                            ("juridica", "Persona Jurídica"),
                        ],
                        default="natural",
                        max_length=10,
                        verbose_name="Tipo de cliente",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                ("telefono", models.CharField(max_length=30, verbose_name="Teléfono")),
                (
                    "telefono_alternativo",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Teléfono alternativo",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=200, verbose_name="Dirección"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        default="activo",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "notas_internas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas internas"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código del proyecto"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, verbose_name="Nombre del proyecto"
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(max_length=200, verbose_name="Ubicación"),
                ),
                (
                    "comuna",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Comuna"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Región"
                    ),
                ),
                (
                    "cantidad_unidades",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad de unidades"
                    ),
                ),
                (
                    "constructora",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Constructora responsable",
                    ),
                ),
                (
                    "encargado",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Encargado del proyecto",
                    ),
                ),
                (
                    "telefono_encargado",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Teléfono encargado",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "fecha_entrega",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de entrega"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("construccion", "En Construcción"),
                            ("entregado", "Entregado"),
                            ("garantia", "En Garantía"),
                            ("finalizado", "Finalizado"),
                        ],
                        default="construccion",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["-fecha_entrega"],
            },
        ),
        migrations.CreateModel(
            name="Reclamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folio",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Folio/Código",
                    ),
                ),
                (
                    "ubicacion_especifica",
                    models.CharField(
                        help_text="Ej: Torre 2, Depto 305",
                        max_length=200,
                        verbose_name="Ubicación específica",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción del problema"),
                ),
                (
                    "tipo_garantia",
                    models.CharField(
                        choices=[
                            ("legal", "Garantía Legal (1 año)"),
                            ("extendida", "Garantía Extendida (3 años)"),
                            ("cortesia", "Cortesía"),
                        ],
                        default="legal",
                        max_length=15,
                        verbose_name="Tipo de garantía",
                    ),
                ),
                (
                    "prioridad",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Muy Alta - Urgente"),
                            (2, "Alta"),
                            (3, "Media"),
                            (4, "Baja"),
                            (5, "Muy Baja"),
                        ],
                        default=3,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("asignado", "Asignado"),
                            ("en_proceso", "En Proceso"),
                            ("resuelto", "Resuelto"),
                            ("cerrado", "Cerrado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_asignacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de asignación"
                    ),
                ),
                (
                    "fecha_primera_visita",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha primera visita"
                    ),
                ),
                (
                    "fecha_estimada_resolucion",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha estimada de resolución",
                    ),
                ),
                (
                    "fecha_resolucion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de resolución"
                    ),
                ),
                (
                    "fecha_cierre",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de cierre"
                    ),
                ),
                (
                    "observaciones_tecnico",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones del técnico"
                    ),
                ),
                (
                    "causa_raiz",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("material_defectuoso", "Material Defectuoso"),
                            ("mala_instalacion", "Mala Instalación"),
                            ("desgaste_normal", "Desgaste Normal"),
                            ("mal_uso", "Mal Uso"),
                            ("otro", "Otro"),
                        ],
                        max_length=25,
                        null=True,
                        verbose_name="Causa raíz",
                    ),
                ),
                (
                    "solucion_aplicada",
                    models.TextField(
                        blank=True, null=True, verbose_name="Solución aplicada"
                    ),
                ),
                (
                    "costo_estimado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Costo estimado",
                    ),
                ),
                (
                    "costo_real",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Costo real",
                    ),
                ),
                (
                    "horas_trabajadas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Horas trabajadas",
                    ),
                ),
                (
                    "materiales_utilizados",
                    models.TextField(
                        blank=True, null=True, verbose_name="Materiales utilizados"
                    ),
                ),
                (
                    "requiere_retiro_escombros",
                    models.BooleanField(
                        default=False, verbose_name="Requiere retiro de escombros"
                    ),
                ),
                (
                    "estado_escombros",
                    models.CharField(
                        choices=[
                            ("no_aplica", "No Aplica"),
                            ("pendiente", "Pendiente"),
                            ("programado", "Programado"),
                            ("retirado", "Retirado"),
                        ],
                        default="no_aplica",
                        max_length=15,
                        verbose_name="Estado retiro escombros",
                    ),
                ),
                (
                    "fecha_retiro_escombros",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha retiro escombros"
                    ),
                ),
                (
                    "comentarios_cliente",
                    models.TextField(
                        blank=True, null=True, verbose_name="Comentarios del cliente"
                    ),
                ),
                (
                    "calificacion_cliente",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1 = Muy insatisfecho, 5 = Muy satisfecho",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Calificación del cliente (1-5)",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="postventa_app.categoria",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="postventa_app.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="postventa_app.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reclamo",
                "verbose_name_plural": "Reclamos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="ImagenReclamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(upload_to="fallas/%Y/%m/", verbose_name="Imagen"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("antes", "Antes"),
                            ("durante", "Durante Reparación"),
                            ("despues", "Después"),
                            ("evidencia", "Evidencia General"),
                        ],
                        default="evidencia",
                        max_length=10,
                        verbose_name="Tipo de imagen",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "subida_por",
                    models.CharField(
                        choices=[
                            ("cliente", "Cliente"),
                            ("tecnico", "Técnico"),
                            ("admin", "Administrador"),
                        ],
                        default="cliente",
                        max_length=10,
                        verbose_name="Subida por",
                    ),
                ),
                (
                    "fecha_subida",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de subida"
                    ),
                ),
                (
                    "reclamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="postventa_app.reclamo",
                        verbose_name="Reclamo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de reclamo",
                "verbose_name_plural": "Imágenes de reclamos",
                "ordering": ["tipo", "fecha_subida"],
            },
        ),
        migrations.CreateModel(
            name="Tecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "especialidad",
                    models.CharField(max_length=100, verbose_name="Especialidad"),
                ),
                ("telefono", models.CharField(max_length=30, verbose_name="Teléfono")),
                (
                    "email_corporativo",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email corporativo",
                    ),
                ),
                (
                    "zonas_cobertura",
                    models.TextField(
                        blank=True,
                        help_text="Comunas o sectores que atiende",
                        null=True,
                        verbose_name="Zonas de cobertura",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("en_terreno", "En Terreno"),
                            ("no_disponible", "No Disponible"),
                            ("vacaciones", "De Vacaciones"),
                        ],
                        default="disponible",
                        max_length=15,
                        verbose_name="Estado actual",
                    ),
                ),
                (
                    "carga_maxima",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Cantidad máxima de casos simultáneos",
                        verbose_name="Carga máxima de casos",
                    ),
                ),
                (
                    "calificacion_promedio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Calificación promedio",
                    ),
                ),
                (
                    "casos_completados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Casos completados"
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de ingreso"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Técnico",
                "verbose_name_plural": "Técnicos",
            },
        ),
        migrations.AddField(
            model_name="reclamo",
            name="tecnico_asignado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="postventa_app.tecnico",
                verbose_name="Técnico asignado",
            ),
        ),
    ]
