# Generated by Django 5.2.7 on 2025-10-23 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Propietario",
                "verbose_name_plural": "Propietarios",
            },
        ),
        migrations.AddField(
            model_name="reclamo",
            name="fecha_compra",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de compra/entrega"
            ),
        ),
        migrations.AddField(
            model_name="reclamo",
            name="unidad",
            field=models.CharField(
                blank=True,
                help_text="Ej: Torre A, Piso 12, Depto 1205",
                max_length=100,
                null=True,
                verbose_name="Unidad/Departamento",
            ),
        ),
        migrations.AlterField(
            model_name="reclamo",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                help_text="Proyecto donde el cliente posee una unidad",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="propietarios",
                to="postventa_app.proyecto",
                verbose_name="Proyecto de vivienda",
            ),
        ),
    ]
