# Generated by Django 5.2.7 on 2025-10-23 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0002_alter_cliente_options_reclamo_fecha_compra_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reclamo",
            name="fecha_compra",
        ),
        migrations.RemoveField(
            model_name="reclamo",
            name="unidad",
        ),
        migrations.AddField(
            model_name="cliente",
            name="fecha_compra",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de compra"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="propietarios",
                to="postventa_app.proyecto",
                verbose_name="Proyecto de vivienda",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="unidad",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Unidad/Departamento",
            ),
        ),
        migrations.AlterField(
            model_name="reclamo",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="postventa_app.proyecto",
                verbose_name="Proyecto",
            ),
        ),
    ]
