# Generated by Django 5.2.7 on 2025-10-24 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0004_inmobiliaria_remove_proyecto_constructora_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Constructora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="RUT Empresa"
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(max_length=200, verbose_name="Razón Social"),
                ),
                (
                    "nombre_comercial",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nombre Comercial",
                    ),
                ),
                (
                    "email_principal",
                    models.EmailField(max_length=254, verbose_name="Email Principal"),
                ),
                ("telefono", models.CharField(max_length=30, verbose_name="Teléfono")),
                (
                    "direccion",
                    models.CharField(max_length=250, verbose_name="Dirección"),
                ),
                (
                    "sitio_web",
                    models.URLField(blank=True, null=True, verbose_name="Sitio Web"),
                ),
                (
                    "nombre_ejecutivo",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nombre Ejecutivo de Cuenta",
                    ),
                ),
                (
                    "email_ejecutivo",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email Ejecutivo",
                    ),
                ),
                (
                    "telefono_ejecutivo",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Teléfono Ejecutivo",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basico", "Básico"),
                            ("profesional", "Profesional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="basico",
                        max_length=15,
                        verbose_name="Plan Contratado",
                    ),
                ),
                (
                    "fecha_inicio_contrato",
                    models.DateField(verbose_name="Inicio de Contrato"),
                ),
                (
                    "fecha_fin_contrato",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin de Contrato"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("suspendido", "Suspendido"),
                            ("inactivo", "Inactivo"),
                        ],
                        default="activo",
                        max_length=12,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
            ],
            options={
                "verbose_name": "Constructora",
                "verbose_name_plural": "Constructoras",
                "ordering": ["razon_social"],
            },
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="inmobiliaria",
        ),
        migrations.AddField(
            model_name="proyecto",
            name="constructora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proyectos",
                to="postventa_app.constructora",
                verbose_name="Constructora",
            ),
        ),
        migrations.AddField(
            model_name="tecnico",
            name="constructora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tecnicos",
                to="postventa_app.constructora",
                verbose_name="Constructora",
            ),
        ),
        migrations.DeleteModel(
            name="Inmobiliaria",
        ),
    ]
