# Generated by Django 5.2.7 on 2025-10-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0005_constructora_remove_proyecto_inmobiliaria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constructora",
            name="plan",
            field=models.CharField(
                choices=[
                    ("basico", "Básico"),
                    ("profesional", "Profesional"),
                    ("corporativo", "Corporativo"),
                ],
                default="basico",
                max_length=15,
                verbose_name="Plan Contratado",
            ),
        ),
    ]
