# Generated by Django 5.2.7 on 2025-10-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0006_alter_constructora_plan"),
    ]

    operations = [
        # Renombrar el modelo Cliente a Propietario
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Propietario',
        ),
        
        # Renombrar campo en Reclamo: cliente -> propietario
        migrations.RenameField(
            model_name='reclamo',
            old_name='cliente',
            new_name='propietario',
        ),
        
        # Renombrar campos de feedback en Reclamo
        migrations.RenameField(
            model_name='reclamo',
            old_name='comentarios_cliente',
            new_name='comentarios_propietario',
        ),
        migrations.RenameField(
            model_name='reclamo',
            old_name='calificacion_cliente',
            new_name='calificacion_propietario',
        ),
        
        # Actualizar max_length y default del campo subida_por en ImagenReclamo
        migrations.AlterField(
            model_name='imagenreclamo',
            name='subida_por',
            field=models.CharField(
                max_length=15,
                choices=[
                    ('propietario', 'Propietario'),
                    ('tecnico', 'Técnico'),
                    ('admin', 'Administrador'),
                ],
                default='propietario',
                verbose_name='Subida por'
            ),
        ),
    ]
