# Generated by Django 5.2.7 on 2025-10-25 13:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0007_rename_cliente_to_propietario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propietario",
            name="tipo_cliente",
        ),
        migrations.AddField(
            model_name="propietario",
            name="tipo_propietario",
            field=models.CharField(
                choices=[
                    ("natural", "Persona Natural"),
                    ("juridica", "Persona Jurídica"),
                ],
                default="natural",
                max_length=10,
                verbose_name="Tipo de propietario",
            ),
        ),
        migrations.AlterField(
            model_name="reclamo",
            name="calificacion_propietario",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="1 = Muy insatisfecho, 5 = Muy satisfecho",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Calificación del propietario (1-5)",
            ),
        ),
        migrations.AlterField(
            model_name="reclamo",
            name="comentarios_propietario",
            field=models.TextField(
                blank=True, null=True, verbose_name="Comentarios del propietario"
            ),
        ),
        migrations.AlterField(
            model_name="reclamo",
            name="propietario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="postventa_app.propietario",
                verbose_name="Propietario",
            ),
        ),
    ]
