# Generated by Django 5.2.7 on 2025-10-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0008_remove_propietario_tipo_cliente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("entregado", "Recién Entregado"),
                    ("garantia", "En Garantía"),
                    ("finalizado", "Garantía Finalizada"),
                ],
                default="entregado",
                max_length=15,
                verbose_name="Estado",
            ),
        ),
    ]
