# Generated by Django 5.2.7 on 2025-10-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0009_eliminar_estado_construccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagenreclamo",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="fallas/%Y/%m/", verbose_name="Imagen"
            ),
        ),
    ]
