# Generated by Django 5.2.7 on 2025-10-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0010_alter_imagenreclamo_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagenreclamo",
            name="imagen",
            field=models.FileField(
                blank=True, null=True, upload_to="fallas/%Y/%m/", verbose_name="Archivo"
            ),
        ),
    ]
