# Generated by Django 5.2.7 on 2025-10-25 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0011_cambiar_imagen_a_archivo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagenreclamo",
            options={
                "ordering": ["tipo", "fecha_subida"],
                "verbose_name": "Archivo de reclamo",
                "verbose_name_plural": "Archivos de reclamos",
            },
        ),
        migrations.AddField(
            model_name="propietario",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="propietario",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario del sistema",
            ),
        ),
    ]
