# Generated by Django 5.2.7 on 2025-10-25 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0012_alter_imagenreclamo_options_propietario_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tecnico",
            name="acepta_agendamiento_online",
            field=models.BooleanField(
                default=True,
                help_text="Si está marcado, los clientes pueden agendar citas directamente",
                verbose_name="Acepta agendamiento online",
            ),
        ),
        migrations.AddField(
            model_name="tecnico",
            name="cantidad_calificaciones",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total de calificaciones recibidas",
                verbose_name="Cantidad de calificaciones",
            ),
        ),
        migrations.AddField(
            model_name="tecnico",
            name="duracion_visita_default",
            field=models.PositiveIntegerField(
                default=120,
                help_text="Tiempo promedio de visita en minutos (default: 120 = 2 horas)",
                verbose_name="Duración de visita (minutos)",
            ),
        ),
        migrations.AddField(
            model_name="tecnico",
            name="especialidades",
            field=models.ManyToManyField(
                blank=True,
                help_text="Categorías de reclamos que puede atender",
                related_name="tecnicos_especializados",
                to="postventa_app.categoria",
                verbose_name="Especialidades",
            ),
        ),
        migrations.AddField(
            model_name="tecnico",
            name="foto_perfil",
            field=models.ImageField(
                blank=True,
                help_text="Foto del técnico (150x150px recomendado)",
                null=True,
                upload_to="tecnicos/fotos/",
                verbose_name="Foto de perfil",
            ),
        ),
        migrations.AddField(
            model_name="tecnico",
            name="proyectos_asignados",
            field=models.ManyToManyField(
                blank=True,
                help_text="Proyectos donde este técnico puede atender",
                related_name="tecnicos_disponibles",
                to="postventa_app.proyecto",
                verbose_name="Proyectos asignados",
            ),
        ),
        migrations.CreateModel(
            name="BloqueoCalendario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de fin")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("vacaciones", "Vacaciones"),
                            ("permiso", "Permiso"),
                            ("capacitacion", "Capacitación"),
                            ("festivo", "Día Festivo"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=15,
                        verbose_name="Tipo de bloqueo",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        help_text="Descripción breve del bloqueo",
                        max_length=200,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "todo_el_dia",
                    models.BooleanField(
                        default=True,
                        help_text="Si es False, especificar hora_inicio y hora_fin",
                        verbose_name="Todo el día",
                    ),
                ),
                (
                    "hora_inicio",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de inicio"
                    ),
                ),
                (
                    "hora_fin",
                    models.TimeField(blank=True, null=True, verbose_name="Hora de fin"),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloqueos",
                        to="postventa_app.tecnico",
                        verbose_name="Técnico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloqueo de calendario",
                "verbose_name_plural": "Bloqueos de calendario",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_cita", models.DateField(verbose_name="Fecha de la cita")),
                ("hora_inicio", models.TimeField(verbose_name="Hora de inicio")),
                ("hora_fin", models.TimeField(verbose_name="Hora de fin")),
                (
                    "duracion_estimada",
                    models.PositiveIntegerField(
                        default=120, verbose_name="Duración estimada (minutos)"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmada", "Confirmada"),
                            ("en_curso", "En Curso"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                            ("reprogramada", "Reprogramada"),
                        ],
                        default="pendiente",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "notas_cliente",
                    models.TextField(
                        blank=True,
                        help_text="Información adicional del propietario",
                        null=True,
                        verbose_name="Notas del cliente",
                    ),
                ),
                (
                    "notas_tecnico",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones del técnico",
                        null=True,
                        verbose_name="Notas del técnico",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_confirmacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de confirmación"
                    ),
                ),
                (
                    "fecha_cancelacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de cancelación"
                    ),
                ),
                (
                    "motivo_cancelacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo de cancelación"
                    ),
                ),
                (
                    "cita_original",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reprogramaciones",
                        to="postventa_app.cita",
                        verbose_name="Cita original",
                    ),
                ),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citas",
                        to="postventa_app.propietario",
                        verbose_name="Propietario",
                    ),
                ),
                (
                    "reclamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citas",
                        to="postventa_app.reclamo",
                        verbose_name="Reclamo",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citas",
                        to="postventa_app.tecnico",
                        verbose_name="Técnico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cita",
                "verbose_name_plural": "Citas",
                "ordering": ["-fecha_cita", "-hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="DisponibilidadTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        verbose_name="Día de la semana",
                    ),
                ),
                ("hora_inicio", models.TimeField(verbose_name="Hora de inicio")),
                ("hora_fin", models.TimeField(verbose_name="Hora de fin")),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar para deshabilitar temporalmente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disponibilidades",
                        to="postventa_app.tecnico",
                        verbose_name="Técnico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disponibilidad de técnico",
                "verbose_name_plural": "Disponibilidades de técnicos",
                "ordering": ["dia_semana", "hora_inicio"],
                "unique_together": {("tecnico", "dia_semana", "hora_inicio")},
            },
        ),
    ]
