# Generated by Django 5.2.7 on 2025-10-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0015_propietario_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propietario",
            name="rut",
            field=models.CharField(max_length=12, verbose_name="RUT/DNI"),
        ),
    ]
