# Generated by Django 5.2.7 on 2025-10-28 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0016_alter_propietario_rut"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reclamo",
            name="prioridad",
        ),
    ]
