# Generated by Django 5.2.7 on 2025-11-01 15:39

import postventa_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0017_remove_reclamo_prioridad"),
    ]

    operations = [
        migrations.AddField(
            model_name="tecnico",
            name="rut",
            field=models.CharField(
                blank=True,
                help_text="Formato libre con puntos/guion (ej: 12.345.678-9). Se normaliza en importación.",
                max_length=12,
                null=True,
                unique=True,
                validators=[postventa_app.models.validate_rut],
                verbose_name="RUT/DNI",
            ),
        ),
    ]
