# Generated by Django 5.2.7 on 2025-11-01 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0018_tecnico_rut"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BitacoraCita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("creada", "Creada"),
                            ("confirmada", "Confirmada"),
                            ("reprogramada", "Reprogramada"),
                            ("cancelada", "Cancelada"),
                            ("completada", "Completada"),
                            ("nota", "Nota"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detalle", models.TextField(blank=True, null=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("old_fecha", models.DateField(blank=True, null=True)),
                ("old_hora_inicio", models.TimeField(blank=True, null=True)),
                ("old_hora_fin", models.TimeField(blank=True, null=True)),
                ("new_fecha", models.DateField(blank=True, null=True)),
                ("new_hora_inicio", models.TimeField(blank=True, null=True)),
                ("new_hora_fin", models.TimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bitacoras",
                        to="postventa_app.cita",
                    ),
                ),
                (
                    "reclamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bitacoras_citas",
                        to="postventa_app.reclamo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bitácora de Cita",
                "verbose_name_plural": "Bitácoras de Cita",
                "ordering": ["-fecha"],
            },
        ),
    ]
