# Generated by Django 5.2.7 on 2025-11-01 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0019_bitacoracita"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reclamo",
            name="estado_escombros",
            field=models.CharField(
                choices=[
                    ("no_aplica", "No Aplica"),
                    ("pendiente", "Pendiente"),
                    ("programado", "Programado"),
                    ("retirado", "Retirado"),
                ],
                default="no_aplica",
                max_length=15,
                verbose_name="Estado retiro escombros (legacy)",
            ),
        ),
        migrations.AlterField(
            model_name="reclamo",
            name="fecha_retiro_escombros",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha retiro escombros (legacy)"
            ),
        ),
        migrations.AlterField(
            model_name="reclamo",
            name="materiales_utilizados",
            field=models.TextField(
                blank=True, null=True, verbose_name="Materiales utilizados (legacy)"
            ),
        ),
        migrations.AlterField(
            model_name="reclamo",
            name="requiere_retiro_escombros",
            field=models.BooleanField(
                default=False, verbose_name="Requiere retiro de escombros (legacy)"
            ),
        ),
        migrations.CreateModel(
            name="Escombro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requiere_retiro",
                    models.BooleanField(default=True, verbose_name="Requiere retiro"),
                ),
                (
                    "volumen_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Volumen estimado (m³)",
                    ),
                ),
                (
                    "tipo_escombro",
                    models.CharField(
                        blank=True,
                        help_text="Ej: escombros de construcción, muebles, electrodomésticos",
                        max_length=100,
                        null=True,
                        verbose_name="Tipo de escombro",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("programado", "Programado"),
                            ("retirado", "Retirado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_programada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha programada de retiro"
                    ),
                ),
                (
                    "fecha_retiro",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha real de retiro"
                    ),
                ),
                (
                    "empresa_retiro",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Empresa de retiro",
                    ),
                ),
                (
                    "costo_retiro",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Costo del retiro",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "reclamo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gestion_escombro",
                        to="postventa_app.reclamo",
                        verbose_name="Reclamo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gestión de Escombro",
                "verbose_name_plural": "Gestión de Escombros",
                "ordering": ["-fecha_programada"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, verbose_name="Nombre del material"
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=8,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        default="unidad",
                        help_text="Ej: metros, litros, unidades, kg",
                        max_length=30,
                        verbose_name="Unidad de medida",
                    ),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Costo unitario",
                    ),
                ),
                (
                    "proveedor",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Proveedor"
                    ),
                ),
                (
                    "fecha_uso",
                    models.DateField(auto_now_add=True, verbose_name="Fecha de uso"),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "reclamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiales",
                        to="postventa_app.reclamo",
                        verbose_name="Reclamo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materiales",
                "ordering": ["-fecha_uso"],
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push"),
                            ("sistema", "Sistema"),
                        ],
                        default="email",
                        max_length=10,
                        verbose_name="Tipo de notificación",
                    ),
                ),
                ("asunto", models.CharField(max_length=200, verbose_name="Asunto")),
                ("mensaje", models.TextField(verbose_name="Mensaje")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("enviada", "Enviada"),
                            ("fallida", "Fallida"),
                            ("leida", "Leída"),
                        ],
                        default="pendiente",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de envío"
                    ),
                ),
                (
                    "fecha_lectura",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de lectura"
                    ),
                ),
                (
                    "intentos_envio",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Intentos de envío"
                    ),
                ),
                (
                    "error_mensaje",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de error"
                    ),
                ),
                (
                    "cita",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notificaciones",
                        to="postventa_app.cita",
                        verbose_name="Cita relacionada",
                    ),
                ),
                (
                    "propietario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="postventa_app.propietario",
                        verbose_name="Propietario",
                    ),
                ),
                (
                    "reclamo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notificaciones",
                        to="postventa_app.reclamo",
                        verbose_name="Reclamo relacionado",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="postventa_app.tecnico",
                        verbose_name="Técnico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
