# Generated by Django 5.2.7 on 2025-11-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postventa_app", "0020_alter_reclamo_estado_escombros_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificacion",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name": "Notificación Email",
                "verbose_name_plural": "Notificaciones Email",
            },
        ),
        migrations.RemoveField(
            model_name="notificacion",
            name="tipo",
        ),
    ]
